//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JigyasyaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionConfig
    {
        public System.Guid Id { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public int HomeMode { get; set; }
        public int ControlType { get; set; }
        public string CenterDescription { get; set; }
        public string TopLeftDescription { get; set; }
        public string TopRightDescription { get; set; }
        public string BottomLeftDescription { get; set; }
        public string BottomRightDescription { get; set; }
        public string SymbolIcon { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    }
}
