//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JigyasyaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GI365_JMSCoreV3Entities : DbContext
    {
        public GI365_JMSCoreV3Entities()
            : base("name=GI365_JMSCoreV3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionConfig> ActionConfigs { get; set; }
        public virtual DbSet<QueryConfig> QueryConfigs { get; set; }
    }
}
